### ISSUE TITLE
LDAP options not validated

### ISSUE THREAD

**Issue by mdschweda** [mdschweda/kubernetes-dashboard-auth#1]
Version: 1.0.1

Not validation takes place with provider `ldap`. Container starts when it should not. Example config:

```yaml
# ...
data:
  auth.provider: ldap
  auth.ldap.server:
  auth.ldap.bindUser:
```
