### ISSUE TITLE
Better user/group acl format

### ISSUE THREAD

**Issue by mdschweda** [mdschweda/kubernetes-dashboard-auth#2]
Version: 1.0.1

ACL entries don't allow equality signs. This makes ldap unusable:

```yaml
data:
  users: |
    ms=kube-system/kubernetes-dashboard-admin
  groups: |
    CN=devs,OU=employees,DC=company,DC=local=kube-system/kubernetes-dashboard-devs
  fallback: kube-system/kubernetes-dashboard
```

... becomes ...

```
acl: {
  users: {
    "ms" : "kube-system/kubernetes-dashboard-admin"
  },
  groups: {
    "CN": "=devs,OU=employees,DC=company,DC=local=kube-system/kubernetes-dashboard-devs"
  },
  fallback: "kube-system/kubernetes-dashboard"
}
```

Could support quotation marks:

```yaml
groups: |
  "a=b"=c
  "a=b"="c=d"
  a="b=\"c\""
```
